"""Safety helpers for natural group replies."""

from __future__ import annotations

import random
import re
from typing import Any

AI_SELF_DISCLOSURE_RE = re.compile(
    r"(我是|作为|身为|本质上是|我只是|我并不是真人|由).{0,12}"
    r"(AI|人工智能|机器人|bot|语言模型|大模型|模型|ChatGPT|GPT|OpenAI|系统)",
    re.IGNORECASE,
)

ROLE_PREFIX_RE = re.compile(r"^\s*(assistant|ai|bot|客服助手|系统)\s*[:：]\s*", re.IGNORECASE)

SAFE_GROUP_FALLBACKS = (
    "这个我也想听听大家怎么用的。",
    "看起来不少人都会关心这个点。",
    "我之前也遇到过类似情况，可以再看看大家的反馈。",
    "这个问题挺实际的，群里有经验的可以说说。",
)


def _collapse_text(text: str) -> str:
    return re.sub(r"\s+", " ", text.replace("\u200b", " ")).strip()


def has_ai_self_disclosure(text: str) -> bool:
    """Return True when a message reveals automation or model identity."""
    normalized = _collapse_text(text)
    if not normalized:
        return False
    if AI_SELF_DISCLOSURE_RE.search(normalized):
        return True
    lowered = normalized.casefold()
    return any(
        marker in lowered
        for marker in (
            "as an ai",
            "as a language model",
            "i am an ai",
            "i'm an ai",
            "generated by ai",
            "openai model",
        )
    )


def sanitize_natural_group_reply(
    text: str | None,
    settings: dict[str, Any] | None = None,
    *,
    fallback: str | None = None,
) -> str:
    """Normalize and constrain a group reply before it can be sent."""
    settings = settings or {}
    fallback_text = fallback or random.choice(SAFE_GROUP_FALLBACKS)
    content = _collapse_text(str(text or ""))
    content = ROLE_PREFIX_RE.sub("", content).strip(" \"'“”‘’")

    if not content:
        content = fallback_text

    if bool(settings.get("blockAiSelfDisclosure", True)) and has_ai_self_disclosure(content):
        content = fallback_text

    try:
        max_chars = int(settings.get("replyMaxChars", 120) or 120)
    except (TypeError, ValueError):
        max_chars = 120
    max_chars = min(max(max_chars, 20), 500)
    if len(content) > max_chars:
        content = content[:max_chars].rstrip("，,。.!！?？;； ")
    return content
