"""
Guardian Moderator Module

Applies moderation decisions generated by the rule engine.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

import structlog
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.account.pool import AccountPool
from app.modules.guardian.moderation.rule_engine import EvaluationResult, GuardianRuleEngine
from app.modules.guardian.moderation.punishment import PunishmentManager, PunishmentResult, PunishmentType

logger = structlog.get_logger()


@dataclass
class ModerationOutcome:
    evaluated: bool
    action_taken: PunishmentType | None = None
    punishment: Optional[PunishmentResult] = None
    deleted: bool = False
    warned: bool = False
    reason: str = ""


class Moderator:
    """Orchestrates moderation evaluation and enforcement."""

    def __init__(self, db: AsyncSession, account_pool: AccountPool, rule_engine: GuardianRuleEngine):
        self.db = db
        self.account_pool = account_pool
        self.rule_engine = rule_engine
        self.punishment_manager = PunishmentManager(db, account_pool)
        self.logger = logger.bind(module="moderator")

    async def handle_message(self, text: str, user_id: int, group_id: int, sender_username: Optional[str] = None) -> ModerationOutcome:
        evaluation = await self.rule_engine.evaluate_message(text, user_id, group_id, sender_username)
        if not evaluation.is_violation:
            return ModerationOutcome(evaluated=True, reason=evaluation.reason)

        punishment = await self._apply_evaluation(evaluation, user_id, group_id)
        return ModerationOutcome(
            evaluated=True,
            action_taken=punishment.punishment_type if punishment else None,
            punishment=punishment,
            deleted=evaluation.should_delete,
            warned=evaluation.should_warn,
            reason=evaluation.reason,
        )

    async def _apply_evaluation(self, evaluation: EvaluationResult, user_id: int, group_id: int) -> Optional[PunishmentResult]:
        action = evaluation.recommended_action
        if action.name == "BAN":
            return await self.punishment_manager.ban(user_id, group_id, reason=evaluation.reason)
        if action.name == "MUTE":
            return await self.punishment_manager.mute(user_id, group_id, duration_seconds=3600, reason=evaluation.reason)
        if action.name == "KICK":
            return await self.punishment_manager.kick(user_id, group_id, reason=evaluation.reason)
        return await self.punishment_manager.warn(user_id, group_id, reason=evaluation.reason)
